# Generated by Django 4.1.1 on 2022-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_CRM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('versao', models.IntegerField(default=1)),
                ('data_criacao', models.DateField()),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField()),
                ('justificativa', models.TextField()),
                ('dependencia', models.BooleanField(default=False)),
                ('mostrar_crm', models.BooleanField(default=True)),
                ('empresa', models.CharField(max_length=50)),
                ('status_crm', models.CharField(choices=[('Em processo', 'em processo'), ('Finalizadas', 'finalizadas'), ('Pendentes', 'pendentes')], default='Pendentes', max_length=50)),
                ('complexidade_crm', models.CharField(blank=True, choices=[('Alta', 'alta'), ('Media', 'media'), ('Baixa', 'baixa')], max_length=50)),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/')),
            ],
        ),
    ]
