# Generated by Django 4.1.1 on 2022-11-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='create_crm',
            constraint=models.UniqueConstraint(fields=('id', 'versao'), name='chave_composta_cadastro_crm'),
        ),
        migrations.AlterModelTable(
            name='create_crm',
            table='create_crm',
        ),
    ]
