# Generated by Django 4.1.1 on 2022-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('CreateCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_crm',
            name='setor',
            field=models.ManyToManyField(to='registration.setor'),
        ),
    ]
