# Generated by Django 4.1.1 on 2022-11-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreateCRM', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.BooleanField(default=False)),
                ('justificativa', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm', to='CreateCRM.create_crm')),
                ('versao_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versao_crm', to='CreateCRM.create_crm')),
            ],
        ),
    ]
