# Generated by Django 4.1.1 on 2022-11-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateCRM', '0002_create_crm_chave_composta_cadastro_crm_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='create_crm',
            name='chave_composta_cadastro_crm',
        ),
        migrations.AlterUniqueTogether(
            name='create_crm',
            unique_together={('id', 'versao')},
        ),
    ]
