# Generated by Django 4.1.1 on 2022-11-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateCRM', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='versao_crm',
            field=models.IntegerField(),
        ),
    ]
