# Generated by Django 4.1.1 on 2022-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateCRM', '0005_alter_create_crm_status_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_crm',
            name='status_crm',
            field=models.CharField(choices=[('Em processo', 'em processo'), ('Finalizadas', 'finalizadas'), ('Pendentes', 'pendentes')], default='Pendentes', max_length=50),
        ),
    ]
