# Generated by Django 4.1.1 on 2022-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateCRM', '0006_alter_create_crm_status_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_crm',
            name='mostrar_crm',
            field=models.BooleanField(default=True),
        ),
    ]
